# execute_llm_select_query.py
def execute_llm_select_query(llm_sql_query: str):
    """
    Executes a SQL query generated by a Large Language Model (LLM) on a Supabase database 
    via a Remote Procedure Call (RPC), while enforcing security and processing results 
    into a consistent JSON format.

    Overview
    --------
    This function allows dynamic execution of SQL queries automatically generated by an 
    LLM based on natural language user input. It provides a secure and standardized mechanism 
    to execute queries against a Supabase database.

    Workflow
    --------
    1. Security Check:
       - Blocks DELETE, UPDATE, INSERT, CREATE, and privilege operations (GRANT, REVOKE)
       - Allows SELECT, JOIN, and other read/write operations

    2. Database Connection:
       - Establishes a connection to Supabase using the `create_supabase_connection` utility.

    3. Query Preparation:
       - Strips whitespace and removes trailing semicolons to ensure clean execution.

    4. Query Execution:
       - Executes the SQL query via the Supabase RPC function named "execute_sql".
       - RPC typically returns each row as a JSON object, e.g., [{'row_to_json': {...}}] or {...}.

    5. Result Processing:
       - Iterates over the returned rows to extract JSON objects.
       - Handles different formats gracefully:
         - If 'row_to_json' key exists, extracts its value.
         - Otherwise, appends the row directly.
       - Returns a consistent list of JSON records.

    6. Error Handling:
       - Catches exceptions during query execution.
       - Returns an error dictionary with descriptive details.

    Parameters
    ----------
    llm_sql_query : str
        The SQL query string generated by the LLM.

    Returns
    -------
    dict
        A dictionary with either:
        - "results": a list of JSON records from the executed query.
        - "error": a descriptive message if execution fails.

    Security Considerations
    -----------------------
    - Blocks DELETE, INSERT, UPDATE, CREATE, GRANT, REVOKE operations
    - Allows SELECT and other operations
    - Should not be used to execute arbitrary SQL from untrusted sources without validation.
    """
    import re
    from connections.Supabase_Connection import create_supabase_connection

    # Security check: Block dangerous operations
    clean_query = llm_sql_query.strip().upper()
    
    # Define forbidden operations
    forbidden_operations = [
        "DELETE",
        "UPDATE",
        "CREATE",
        "DROP",
        "TRUNCATE",
        "ALTER",
        "GRANT",
        "REVOKE"
    ]
    
    # Check if query contains any forbidden operations
    for operation in forbidden_operations:
        # Using regex to match whole words only
        pattern = r'\b' + re.escape(operation) + r'\b'
        if re.search(pattern, clean_query):
            raise ValueError(f"Operation '{operation}' is not allowed for security reasons.")

    # Create Supabase connection
    supabase = create_supabase_connection()

    # Clean query: remove whitespace and trailing semicolons
    llm_sql_query = llm_sql_query.strip().rstrip(";")

    try:
        # Execute the query via RPC
        result = supabase.rpc("execute_sql", {"query": llm_sql_query}).execute()

        # Process returned rows into a list of JSON objects
        records = []
        if result.data:
            for row in result.data:
                # Check if row contains 'row_to_json' key
                if isinstance(row, dict) and 'row_to_json' in row:
                    records.append(row['row_to_json'])
                else:
                    # Append row directly if already JSON
                    records.append(row)
        
        return {"results": records}

    except Exception as e:
        # Handle exceptions and return as error dictionary
        print(f"Error details: {str(e)}")
        return {"error": f"Query execution failed: {str(e)}"}
